import React, { useState, useEffect } from 'react';
import { Calendar, Zap, RefreshCw, CheckCircle, Sun, Sunset, Moon, Star, Clock } from 'lucide-react';
import { aiGenerate } from '../services/ai';
import { DAILY_PLAN_TEMPLATE } from '../data/examData';

const GOALS = [
  { id: 'entrance', label: 'NEET / JEE / CUET', color: 'orange' },
  { id: 'govt', label: 'UPSC / TNPSC / SSC', color: 'blue' },
  { id: 'placement', label: 'IT Placement (TCS/Infy/etc.)', color: 'purple' },
  { id: 'product', label: 'Product Company / Startup', color: 'cyan' },
];

const DURATIONS = [
  { id: '1week', label: '7-Day Sprint', desc: 'Crash course, intensive' },
  { id: '1month', label: '30-Day Plan', desc: 'Focused and structured' },
  { id: '3months', label: '90-Day Plan', desc: 'Comprehensive coverage' },
  { id: '6months', label: '6-Month Journey', desc: 'Full syllabus mastery' },
];

const TIME_AVAILABLE = [
  { id: '2', label: '2 Hours/Day', desc: 'Busy schedule' },
  { id: '4', label: '4 Hours/Day', desc: 'Moderate focus' },
  { id: '6', label: '6 Hours/Day', desc: 'Serious preparation' },
  { id: '10', label: '10+ Hours/Day', desc: 'Full-time prep' },
];

const SlotIcon = ({ slot }) => {
  if (slot === 'morning') return <Sun size={16} color="var(--neon-yellow)" />;
  if (slot === 'afternoon') return <Sunset size={16} color="var(--neon-primary)" />;
  if (slot === 'evening') return <Star size={16} color="var(--neon-purple)" />;
  return <Moon size={16} color="var(--neon-blue)" />;
};

const StudyPlan = ({ userGoal }) => {
  const [goal, setGoal] = useState(userGoal || 'entrance');
  const [duration, setDuration] = useState('1month');
  const [hoursPerDay, setHoursPerDay] = useState('6');
  const [weakTopics, setWeakTopics] = useState('');
  const [plan, setPlan] = useState(null);
  const [loading, setLoading] = useState(false);
  const [todayPlan, setTodayPlan] = useState(DAILY_PLAN_TEMPLATE(userGoal || 'entrance'));
  const [completedTasks, setCompletedTasks] = useState({});

  const generatePlan = async () => {
    setLoading(true);
    setPlan(null);
    const goalLabel = GOALS.find(g => g.id === goal)?.label;
    const durLabel = DURATIONS.find(d => d.id === duration)?.label;

    const prompt = `Create a detailed ${durLabel} study plan for a student preparing for ${goalLabel}.
Available time: ${hoursPerDay} hours per day.
Weak topics mentioned: ${weakTopics || 'None specified'}.

Format your response as a structured weekly plan with:
1. Week-wise breakdown
2. Daily topic allocation
3. Mock test schedule
4. Revision strategy

Be specific with subject names, chapter names, and time allocation. Make it actionable.`;

    try {
      let result = '';
      await aiGenerate(prompt, (_, full) => { result = full; });
      setPlan(result);
    } catch (err) {
      setPlan(`**Error generating plan:** ${err.message}\n\nPlease try again later.`);
    } finally {
      setLoading(false);
    }
  };

  const toggleTask = (slot, idx) => {
    const key = `${slot}-${idx}`;
    setCompletedTasks(prev => ({ ...prev, [key]: !prev[key] }));
  };

  return (
    <div>
      <div className="section-header">
        <div>
          <div className="section-title">AI Study Planner</div>
          <div className="section-desc">Get a personalized study plan generated by AGNI AI</div>
        </div>
      </div>

      <div className="grid-2" style={{ gap: 20, marginBottom: 24 }}>
        {/* Plan Generator */}
        <div className="card card-glow-orange">
          <div style={{ fontWeight: 700, color: 'var(--text-primary)', marginBottom: 18, fontSize: '0.95rem', display: 'flex', gap: 8, alignItems: 'center' }}>
            <Zap size={16} color="var(--neon-primary)" /> Generate AI Plan
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
            <div className="input-group">
              <label className="input-label">Your Goal</label>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                {GOALS.map(g => (
                  <button key={g.id} onClick={() => setGoal(g.id)}
                    style={{
                      padding: '9px 14px', borderRadius: 8, border: `1px solid ${goal === g.id ? `rgba(249,115,22,0.4)` : 'var(--border)'}`,
                      background: goal === g.id ? 'rgba(249,115,22,0.1)' : 'var(--bg-input)',
                      color: goal === g.id ? 'var(--neon-primary)' : 'var(--text-secondary)',
                      cursor: 'pointer', textAlign: 'left', fontSize: '0.85rem', fontWeight: goal === g.id ? 600 : 400,
                      display: 'flex', alignItems: 'center', gap: 8,
                    }}>
                    {goal === g.id && <CheckCircle size={15} color="var(--neon-primary)" />}
                    {g.label}
                  </button>
                ))}
              </div>
            </div>

            <div className="input-group">
              <label className="input-label">Plan Duration</label>
              <select className="input" value={duration} onChange={e => setDuration(e.target.value)}>
                {DURATIONS.map(d => <option key={d.id} value={d.id}>{d.label} — {d.desc}</option>)}
              </select>
            </div>

            <div className="input-group">
              <label className="input-label">Daily Study Hours</label>
              <select className="input" value={hoursPerDay} onChange={e => setHoursPerDay(e.target.value)}>
                {TIME_AVAILABLE.map(t => <option key={t.id} value={t.id}>{t.label} — {t.desc}</option>)}
              </select>
            </div>

            <div className="input-group">
              <label className="input-label">Your Weak Topics (optional)</label>
              <textarea className="input" rows={3} value={weakTopics} onChange={e => setWeakTopics(e.target.value)}
                placeholder="e.g. Organic chemistry, Integration, Current affairs..." />
            </div>

            <button className="btn btn-primary" onClick={generatePlan} disabled={loading}>
              {loading ? <><div className="spinner" style={{ width: 16, height: 16 }} /> AI Generating Plan...</> : <><Zap size={16} /> Generate My Plan</>}
            </button>
          </div>
        </div>

        {/* Today's Plan */}
        <div className="card card-glow-blue">
          <div style={{ fontWeight: 700, color: 'var(--text-primary)', marginBottom: 18, fontSize: '0.95rem', display: 'flex', gap: 8, alignItems: 'center' }}>
            <Calendar size={16} color="var(--neon-blue)" /> Today's Schedule
          </div>

          {Object.entries(todayPlan).map(([slot, tasks]) => (
            <div key={slot} style={{ marginBottom: 18 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 7, marginBottom: 10 }}>
                <SlotIcon slot={slot} />
                <span style={{ fontWeight: 600, fontSize: '0.82rem', color: 'var(--text-secondary)', textTransform: 'capitalize' }}>{slot}</span>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                {tasks.map((task, i) => {
                  const key = `${slot}-${i}`;
                  const done = completedTasks[key];
                  return (
                    <div key={i} onClick={() => toggleTask(slot, i)}
                      style={{
                        display: 'flex', alignItems: 'center', gap: 10,
                        padding: '9px 12px', borderRadius: 8,
                        background: done ? 'rgba(16,185,129,0.06)' : 'rgba(255,255,255,0.02)',
                        border: `1px solid ${done ? 'rgba(16,185,129,0.2)' : 'var(--border)'}`,
                        cursor: 'pointer', transition: 'all 0.15s',
                      }}>
                      <div style={{
                        width: 18, height: 18, borderRadius: 5, flexShrink: 0,
                        background: done ? 'var(--neon-green)' : 'transparent',
                        border: `2px solid ${done ? 'var(--neon-green)' : 'var(--text-muted)'}`,
                        display: 'flex', alignItems: 'center', justifyContent: 'center',
                      }}>
                        {done && <CheckCircle size={12} color="#000" />}
                      </div>
                      <span style={{ fontSize: '0.82rem', color: done ? 'var(--text-muted)' : 'var(--text-secondary)', textDecoration: done ? 'line-through' : 'none' }}>
                        {task}
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>
          ))}

          <div style={{ marginTop: 8, padding: '10px 14px', background: 'rgba(59,130,246,0.06)', borderRadius: 10, border: '1px solid rgba(59,130,246,0.15)' }}>
            <div style={{ fontSize: '0.78rem', color: 'var(--neon-blue)', fontWeight: 600 }}>
              {Object.values(completedTasks).filter(Boolean).length} / {Object.values(todayPlan).flat().length} tasks completed today
            </div>
          </div>
        </div>
      </div>

      {/* Generated Plan */}
      {plan && (
        <div className="card card-glow-green" style={{ marginTop: 8 }}>
          <div style={{ fontWeight: 700, color: 'var(--text-primary)', marginBottom: 16, fontSize: '0.95rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={{ display: 'flex', gap: 8, alignItems: 'center' }}><Calendar size={16} color="var(--neon-green)" /> AI-Generated Study Plan</span>
            <button className="btn btn-secondary btn-sm" onClick={generatePlan}><RefreshCw size={13} /> Regenerate</button>
          </div>
          <div style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', lineHeight: 1.8, whiteSpace: 'pre-wrap', fontFamily: 'var(--font-main)' }}>
            {plan}
          </div>
        </div>
      )}
    </div>
  );
};

export default StudyPlan;
